### ISSUE TITLE
Database returns no tables.

### ISSUE THREAD

**Issue by themadhatterz** [CPDTAC/CPViewInsights#18]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/dash/dash.py", line 541, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/usr/local/lib/python3.5/dist-packages/dash/dash.py", line 498, in add_context
    output_value = func(*args, **kwargs)
  File "/var/www/cviweb/insight.py", line 118, in pull_tables
    table_list = custom.table_selection(database)
  File "/var/www/cviweb/custom.py", line 40, in table_selection
    db = sqlite3.connect(database)
sqlite3.OperationalError: unable to open database file

Likely due to CPViewDB not being exported properly. 
Need to investigate if there is a better way to get partial information if possible, or simply return that the database is potentially corrupt and be sure to educate the appropriate export procedure.

**Comment by themadhatterz** [comment]
@kyle-danielson 
Want to address this as Version 0.1.1 bug fix?

**Comment by themadhatterz** [comment]
Analyzed the file locally on the server, the file did not have read permission. Once added, tables were displayed.

**Comment by themadhatterz** [comment]
Project is moving.
